### ISSUE TITLE
What to do when my project uses ember-modifier@v4

### ISSUE THREAD

**Issue by NullVoxPopuli** [ijlee2/ember-container-query#143]
## Describe the bug 🐞

When using ember-modifier v4 and ember-container-query v3, I get the following error during build time:
```
ember-container-query needs to depend on ember-auto-import in order to use ember-modifier
```
I saw that in the package.json, that ember-auto-import is not a dependency.
Maybe we can group a few things together:

Things we need
 - add ember-auto-import@v2 as a dependency (non-breaking? idk actually)
 - convert to v2 addon (optional, but highly recommended, as when all addons are v2, we can see build times drop to half of what they are now) -- we'd then no longer need ember-auto-import-v2
 - widen support for ember-modifier to v3 and v4 _or_ change ember-modifier to be a _peerDependency_ so we don't get multiple copies of ember-modifier attempted to be resolved in a consuming app.

## Expected behavior 🤔

To be able to boot my app.

## Minimal reproduction 🔬

Describe steps to reproduce the behavior:
1. Use ember-container-query with ember-modifier-3
2. Use ember-modifier v4
3. try to boot your app
4. error

https://github.com/NullVoxPopuli/limber/pull/621

## Environment 🌍

- Ember: - n/a
- Node.js/npm: - Node 18, pnpm v7.x

**Comment by ijlee2** [comment]
@NullVoxPopuli Thanks for using `ember-container-query` (I do need more examples) and reporting the issue with possible solutions.

My understanding was that, with `ember-modifier@v4`, this addon wouldn't be able to support projects that can't use `ember-auto-import@v2` at the moment. So, for the `v3.0.0` release, I limited the version of `ember-modifier` to `v3.2.7`.

(For this addon's `v4` release, I do plan to support v2 addon format and list `ember-auto-import@v2` as a dependency, so I'm glad to see your suggestions here.)

I had tested `v3.0.0-alpha.0` in [`ember-workshop`](https://github.com/ijlee2/ember-workshop). This project uses `ember-modifier@v4` for its own modifiers, but allows multiple versions of `ember-modifier` to be installed. I noticed that the `limber` project uses pnpm resolutions; I wonder if it's possible to remove the resolution for `ember-modifier` for the time being.

I'll need some time to figure out the right solution. I'll keep an eye out for what other addons that depend on `ember-modifier` do.

**Comment by NullVoxPopuli** [comment]
I'm not using any resolutions atm in limber -- but i did tell pnpm to not log the error about me having ember-modifier at a newer version. I could probably remove that now that i've patched container query. Good eye!

Yarn1 is inherently flawed for basically everything and i can't trust that it's resolving things correctly.
I've wasted weeks of my life dealing with yarn related bugs. 😢

**Comment by ijlee2** [comment]
Oh. I did a superficial review of your pull request, and might have misunderstood how resolutions work in `pnpm`. From the following line, I thought that you had installed just one version of `ember-modifier` (`v4`):

- https://github.com/NullVoxPopuli/limber/blob/c5c6b88dec0b1542550a1d2d90378581e1b2aebc/pnpm-lock.yaml#L6

**Comment by NullVoxPopuli** [comment]
Oh! No, I'm a space cadet and will remove that!
Thank you <3

**Comment by NullVoxPopuli** [comment]
Done here: https://github.com/NullVoxPopuli/limber/pull/623 

it _should_ work about the same -- because the error was reported from ember-cli-dependency-checker (or whatever it's called), and pnpm only _organizes_ the deps correctly (compared to yarn)

**Comment by ijlee2** [comment]
To recap, my current suggestion to the users is to allow multiple versions of `ember-modifier` (e.g. `v3` and `v4`) to be installed. If [`ember-cli-dependency-lint`](https://github.com/salsify/ember-cli-dependency-lint) has been installed, they may need to [update the configuration file](https://github.com/salsify/ember-cli-dependency-lint/tree/v2.0.1#allowed-versions).

Once `ember-container-query@v4.0.0` is released (see #144 for plans), we can mark this issue as fixed.

**Comment by NullVoxPopuli** [comment]
seems like a reasonable work around for now -- esp if folks have big apps where a duplicate dependency shipped to their users doesn't impact them much. nice!

**Comment by ijlee2** [comment]
End-developers who would like to use `ember-modifier@v4` may install `ember-container-query@v4.0.0-alpha.3` (if they are okay with an alpha release).
