### ISSUE TITLE
Research `ResizeObserver`-based modifiers

### ISSUE THREAD

**Issue by ijlee2** [ijlee2/ember-container-query#47]
## I would like to see... 🙋‍♀️🙋‍♂️

[`ember-did-resize-modifier`](https://github.com/gmurphey/ember-did-resize-modifier) relies on [`element-resize-detector`](https://github.com/wnr/element-resize-detector), which uses a custom solution to detecting element resize (it was backed by research).

The addon works well. There has also been a growing development in a modifier that uses native [`ResizeObserver`](https://developer.mozilla.org/docs/Web/API/ResizeObserver) API. Let's investigate if now is a good time to switch the resize modifier to one that uses native JavaScript API.

## Why and how 💬

Modifiers help us develop a composable solution. If I separated concerns for a container query correctly, we should be able to switch the resize modifier _without making a breaking change_. 

Research what these solutions do and don't do well:

- [`element-resize-detector`](https://arxiv.org/pdf/1511.01223v1.pdf)
- [`ember-on-resize-modifier`](https://github.com/PrecisionNutrition/ember-on-resize-modifier)
- [`ember-resize-modifier`](https://github.com/elwayman02/ember-resize-modifier)
- [`ember-resize-observer-modifier`](https://github.com/alexlafroscia/ember-resize-observer-modifier)

Since a resize modifier is an integral dependency, let's look into their commitment to stability (documentation, testing, and maintenance).

## Additional context ➕

I imagine that, in a real-world app, O(10¹) resizes can happen at the same time (not just 1 or 2 resizes). Rather than eyeballing each modifier's performance, see if we can reliably measure the resize performance in testing and do a health check in CI.

- [`TracerBench`](https://github.com/TracerBench/tracerbench)

**Comment by st-h** [comment]
Hey, I am currently looking for a way to make container queries happen. Personally, I would just replace `ember-did-resize-modifier` with `ember-on-resize-modifier`, which should give you all the benefits of using a resize observer. I have been using `ember-on-resize-modifier` for a while and it seems to work wonderfully.

**Comment by ijlee2** [comment]
Hi, @st-h. Thanks for providing feedback that container queries matter to you and your apps. 🙂

I haven't recently worked on investigating the use of 3 modifiers listed above, but would be glad to try them out again (`ember-on-resize-modifier`, in particular). Would you like to help out by making a pull request?

---

Around July 2020, I tried replacing `ember-did-resize-modifier` with the 3 modifiers. For every one of them, I saw a performance issue in resize (or rerender, I suppose) in the [Dashboard page](https://ember-container-query.netlify.app/dashboard)—I believe, due to the D3 component (Widget 2).

At the time, I wasn't sure if I coded how to rerender D3 chart incorrectly, or if I used the 3 modifiers incorrectly, or something else. I wasn't also sure how to measure performance so that I could quantitatively describe the impact of replacing `ember-did-resize-modifier`.

If you could fork this repo and try replacing `ember-did-resize-modifier` and `ember-on-resize-modifier`, I think that would make a good start to solving this issue. 👍🏼

---

Will you let me know what you think of the suggested path forward? Thanks again for providing your feedback!

**Comment by st-h** [comment]
Thanks for your response. Actually, I wrote a naive implementation of container queries myself using `ember-on-resize-modifier` and a few css classes. Yet, it turned out, it was going to be quite difficult to nest multiple instances of it. 

My intention was to try to replace `ember-did-resize-modifier` as soon as I can find a solution that works reliably in our app. I was running into a few scenarios where ember-container-query would get into an infinite loop, constantly swapping out the currently active feature. I think this can be worked around by being careful where to actually place the `<ContainerQuery>`. Also I found the default styles that are applied to cause some issues in some cases.

**Comment by st-h** [comment]
I've been trying out using `ember-on-resize-modifier` and the fork seems to be working fine within our app. Not sure atm why some test are failing. Seems like some of them are testing immutability, which I am not sure why this is an issue now.

**Comment by st-h** [comment]
Oh, what do you think about making the default unit ems instead of px? Probably this should be configurable, or both should be supported in some way, but I feel often ems are more useful than pxs...

**Comment by ijlee2** [comment]
Hi, @st-h. I haven't had time to review your pull request yet, sorry. I will try to find time to do so this weekend.

With regards to `em`, I think it's good to keep the default unit in pixels. I don't use `em` myself (`rem`, I do) so I'm currently unsure what is a particular use-case that you would like to solve with `em` and container query. Could you explain your use case to me?

**Comment by st-h** [comment]
Honestly, I am surely not an expert regarding sizing and their units. But, afaik the main thing is that when changing the base font size of the body (which apparently is a thing some users actually do), the whole page will scale if built using `em`. If one uses `px` everywhere, usually the font size changes, but everything that is specified using `px` will not scale (so things that aligned in its default state will no longer align). From what I have been researching and reading within the last years, it seems to be pretty common and recommended practice to mainly use `em`. I was using `px` a lot in the past, but so far have been moving things over to `em` where there is no reason to use `px` and it's been working out really well.

I have been using my fork for few days for local dev and on our beta frontend, and so far it seems to be working without issue.

**Comment by st-h** [comment]
Ok, I just came across this https://css-tricks.com/em-based-media-queries-are-based-on/ after running into some issues with my media queries. So, essentially it's not possible to reliable convert `em` to `px` within media queries, as I don't know how to differentiate if the font size is set on the body or using the browser settings. So using `em`s for media queries just seems to introduce more issues than it solves. (I was also under the impression, that the font size set on the body would be applied in any case, as this is the case with `em`s otherwise)
