### ISSUE TITLE
Install ember-truth-helpers for demo app

### ISSUE THREAD

**Issue by ijlee2** [ijlee2/ember-container-query#59]
## I would like to see... 🙋‍♀️🙋‍♂️

When I first designed the demo app, I wrote custom logic helpers `and`, `eq`, and `or` as they became needed. In hindsight, I should have installed [ember-truth-helpers](https://github.com/jmurphyau/ember-truth-helpers) instead.

## Why and how 💬

A core idea behind Ember is shared solutions. Rather than reinventing the wheel, let's install a time-proven addon to maintain the demo app. This will also help the demo app better match the environment under which an addon user might be developing their own app.

After installing the addon, please remove the custom helpers and rendering tests (if there are any).

## Additional context ➕

Please follow the [Installation](https://github.com/jmurphyau/ember-truth-helpers#installation) instructions and check that `package.json` lists `ember-truth-helpers` in `devDependencies`.

**Comment by ijlee2** [comment]
General notes: To allow more people to participate in Hacktoberfest, please claim only 1 issue (unless there are no others who can help). 🙂

**Comment by vvkpd** [comment]
I would like to work on this card, could you please assign to me?
Thanks!

**Comment by ijlee2** [comment]
Hi, @vvkpd . Thanks for your interest in helping out with `ember-container-query`. Let me know if you have questions!

**Comment by ijlee2** [comment]
Hi, @vvkpd. I want to make a release shortly after October ends. I'll be accepting @esbanarango's pull request.
