### ISSUE TITLE
Support mutations due to async-loaded data

### ISSUE THREAD

**Issue by NullVoxPopuli** [ijlee2/ember-container-query#95]
Hello! Thanks for taking time to suggest how we can improve `ember-container-query`.

Before you make a new issue, please search for similar issues. It's possible that someone has made a request aleady.

## I would like to see... 🙋‍♀️🙋‍♂️

It seems like ContainerQuery only runs on resizes -- which means that if a render occurs that does not trigger a resize and has some loading / intermediate state, the container query update does not occur

## Why and how 💬

Maybe this would need MutationObserver?

atm, my taking-a-while content finishes loading after container query runs, so then my content is squished because there is not enough room (incorrect classes applied, because container query thinks there is sufficient space)

## Additional context ➕

If needed, you can provide more context (e.g. reference materials, screenshots, GIFs) for the request here.

**Comment by ijlee2** [comment]
Hi, @NullVoxPopuli. Thanks for opening an issue to describe a problem that you had encountered.

I think I'd like to see a more concrete example, to better understand how you might be trying to render the content. Could you provide me a skeleton code?

Per design, `ember-container-query` is only concerned with a resize to the container. If I understood your problem correctly, I think it wouldn't be a good idea for this addon to mix concerns with, e.g. data loading and listening to DOM changes via MutationObserver. However, the consuming developer is welcome to compose this addon with another to solve such problem.

**Comment by ijlee2** [comment]
I'll close this issue for the time being, as the requested feature is not on my roadmap to `v4`. We can always re-open the issue later when the described problem is relevant.
